name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  setup-sample-data:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Install ts-node Globally
        run: npm install -g ts-node typescript

      - name: Run remove_db.ts Script
        run: ts-node remove_db.ts

      - name: Run insert_sample_db.ts Script
        run: ts-node insert_sample_db.ts