name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  setup-sample-data:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Delete old database
        run: ts-node remove_db.ts -- "mongodb://127.0.0.1:27017/my_library_db"

      - name: add database
        run: ts-node insert_sample_db.ts -- "mongodb://127.0.0.1:27017/my_library_db"